server:
  port: 8085

spring:
  application:
    name: training-course-service

  datasource:
    url: jdbc:h2:mem:coursedb

  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: update

  h2:
    console:
      enabled: true

  liquibase:
    enabled: false
